"""Added QRCode table and relationship with user

Revision ID: 65ca683af32f
Revises: fb5580d7da6d
Create Date: 2022-02-09 18:49:30.868353

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65ca683af32f'
down_revision = 'fb5580d7da6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('qrcodes',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('delete_hash', sa.String(length=255), nullable=False),
    sa.Column('link', sa.String(length=512), nullable=False),
    sa.Column('content', sa.String(length=512), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('delete_hash'),
    sa.UniqueConstraint('link')
    )
    op.create_index(op.f('ix_qrcodes_id'), 'qrcodes', ['id'], unique=False)
    op.add_column('users', sa.Column('date_created', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'date_created')
    op.drop_index(op.f('ix_qrcodes_id'), table_name='qrcodes')
    op.drop_table('qrcodes')
    # ### end Alembic commands ###
